# Generated by Django 4.2.6 on 2023-11-24 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=32, unique=True)),
                ('expiration_date', models.DateField()),
                ('strike', models.DecimalField(decimal_places=2, max_digits=10)),
                ('option_type', models.CharField(choices=[('C', 'Call'), ('P', 'Put')], help_text='Option Type: Put or Call', max_length=1)),
            ],
            options={
                'ordering': ['expiration_date', 'symbol', 'strike'],
            },
        ),
        migrations.CreateModel(
            name='OptionQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.option')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_type', models.CharField(choices=[('O', 'Option'), ('S', 'Stock')], help_text='Stock or Option Type', max_length=1)),
                ('name', models.CharField(default='Default', max_length=32)),
                ('option', models.ManyToManyField(blank=True, through='portfolio.OptionQuantity', to='portfolio.option')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['owner'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='StockQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.portfolio')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.stock')),
            ],
        ),
        migrations.AddField(
            model_name='portfolio',
            name='stock',
            field=models.ManyToManyField(blank=True, through='portfolio.StockQuantity', to='portfolio.stock'),
        ),
        migrations.AddField(
            model_name='optionquantity',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.portfolio'),
        ),
        migrations.AddField(
            model_name='option',
            name='underlying',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.stock'),
        ),
        migrations.AlterUniqueTogether(
            name='portfolio',
            unique_together={('name', 'owner')},
        ),
        migrations.AlterUniqueTogether(
            name='option',
            unique_together={('underlying', 'expiration_date', 'strike', 'option_type')},
        ),
    ]
