# Generated by Django 4.2.6 on 2023-11-24 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='instrument_type',
        ),
    ]
