# Generated by Django 4.2.6 on 2023-11-24 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='option',
            field=models.ManyToManyField(blank=True, to='portfolio.option'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='stock',
            field=models.ManyToManyField(blank=True, to='portfolio.stock'),
        ),
    ]
