# Generated by Django 4.2.6 on 2023-11-25 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_remove_portfolio_instrument_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='delta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='option',
            name='gamma',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='option',
            name='iv',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='option',
            name='open_interest',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='option',
            name='theta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='option',
            name='vega',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='option',
            name='volume',
            field=models.IntegerField(default=0),
        ),
    ]
