# Generated by Django 4.2.6 on 2023-11-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_portfolio_option_alter_portfolio_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='name',
            field=models.CharField(default='Default', max_length=32, unique=True),
        ),
    ]
