# Generated by Django 4.2.6 on 2023-11-25 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_option_delta_option_gamma_option_iv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='delta',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='option',
            name='gamma',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='option',
            name='iv',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='option',
            name='theta',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='option',
            name='vega',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
